# Generated by Django 3.1 on 2020-10-31 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstype',
            name='image',
            field=models.ImageField(max_length=200, upload_to='type', verbose_name='商品类型图片'),
        ),
    ]
