# Generated by Django 3.1 on 2020-11-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20201102_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodssku',
            options={'verbose_name': '商品SKU', 'verbose_name_plural': '商品SKU'},
        ),
        migrations.AlterModelOptions(
            name='indextypegoodsbanner',
            options={'verbose_name': '主页分类商品', 'verbose_name_plural': '主页分类商品'},
        ),
    ]
