# Generated by Django 3.1 on 2020-11-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200823_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='comment',
            field=models.CharField(max_length=256, null=True, verbose_name='评论'),
        ),
    ]
